---
name: 'Test package building for specific distributions'

on:
  workflow_dispatch:

jobs:
  build:
    name: build.sh
    # on a ubuntu-20.04 VM
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        product: ['recursor']
        os:
          - centos-7
          - centos-8
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 5
          submodules: recursive
      # this builds packages and runs our unit test (make check)
      - run: builder/build.sh -v -m ${{ matrix.product }} ${{ matrix.os }}
      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: /home/runner/work/pdns/pdns/builder/tmp/**/x86_64/pdns-recursor*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
